# Generado por wallust — colors de kitty.
# Incluido al final de kitty.conf con: include colors-wallust.conf

foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #CDD6F4

cursor                  #CDD6F4
cursor_text_color       #1E1E2E

url_color               #CBA6F7

active_border_color     #CBA6F7
inactive_border_color   #585B70
bell_border_color       #F9E2AF

active_tab_foreground   #1E1E2E
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #585B70

color0  #11111B
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #CBA6F7
color6  #94E2D5
color7  #CDD6F4
color8  #585B70
color9  #EBA0AC
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #F5C2E7
color14 #94E2D5
color15 #A6ADC8
