#!/bin/sh
file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

draw() {
  kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

video() {
  thumb="/tmp/lf-video-thumb-$(stat -c %i "$1").jpg"
  if [ ! -f "$thumb" ]; then
      ffmpegthumbnailer -i "$1" -o "$thumb" -s 0 2>/dev/null
  fi
  draw "$thumb"
}

pdf() {
  thumb="/tmp/lf-pdf-thumb-$(stat -c %i "$1").jpg"
  
  if [ ! -f "$thumb" ]; then
      pdftoppm -f 1 -l 1 -scale-to-x 1920 -jpeg -singlefile "$1" "${thumb%.jpg}" 2>/dev/null
  fi
  
  draw "$thumb"
}

archive() {
  case "$1" in
    *.tar*) tar tf "$1" 2>&1 ;;
    *.zip) unzip -l "$1" 2>&1 ;;
    *.rar) unrar l "$1" 2>&1 ;;
    *.7z) 7z l "$1" 2>&1 ;;
    *.iso) bsdtar --list --file "$1" 2>&1 ;;
    *) echo "Extensión no soportada." ;;
  esac
  exit 1
}

mime="$(file -Lb --mime-type "$file")"
case "$mime" in 
  image/*)
    draw "$file"
    ;;
  video/*)
    video "$file"
    ;;
  application/pdf)
    pdf "$file"
    ;;
esac

case "$file" in
  *.zip|*.jar|*.war|*.ear|*.oxt)
    archive "$file"
    ;;
  *.tar|*.tar.*|*.tgz|*.tbz2)
    archive "$file"
    ;;
  *.rar)
    archive "$file"
    ;;
  *.7z)
    archive "$file"
    ;;
  *.iso)
    archive "$file"
    ;;
esac

COLORTERM=truecolor bat --color=always --style=numbers --wrap=character --terminal-width="$((w - 2))" --paging=never "$file"
