$LOVE = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/My love.jpeg
$LOVE2 = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/My-love-v2.png
$DD01 = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/IMG0020.jpg
$DD04 = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/DD04.jpg
$OSAKA = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/osaka.jpg
$SAMURAI = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/fantasy-samurai-kimono-full-moon.jpg
$BURNINGCHERRY = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/burningcherry.jpeg
$SWORD = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/sword-8k-wallpaperjpg
$GIRL = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/anime-girl.jpg
$SWORD2 = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/sword-red-eyes.jpg
$NIGHT = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/night-city-full-moon.jpg
$GUTS = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/Guts.jpg
$SAURON = ~/Di3go0-0_dots/Resources/wallpapers/Illustration/sauron-lord.jpg
$DRAGON = ~/Di3go0-0_dots/Resources/wallpapers/Illustration/dragon-fantasy.jpg
$KNIGHT = ~/Di3go0-0_dots/Resources/wallpapers/Illustration/fantasy-knight-cat.jpg
$SCARY = ~/Di3go0-0_dots/Resources/wallpapers/Illustration/girl-scary.jpg
$GIRL2 = ~/Di3go0-0_dots/Resources/wallpapers/Illustration/girl-red-eyes.jpg

# Preload
preload = $DD01
preload = $OSAKA
preload = $BURNINGCHERRY
preload = $SWORD
preload = $SWORD2
preload = $DD04
preload = $NIGHT

wallpaper {
    monitor = eDP-2
    path = $SAMURAI
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = $SAMURAI
    fit_mode = cover
}

splash = true

