# ────────────────────────────────────────────────────────────
#  Hyprlock — minimal blur with ringed input
# ────────────────────────────────────────────────────────────

general {
    grace = 0
    hide_cursor = true
}

# $LAYOUT_PATH=~/.config/hypr/hyprlock/Arfan on Clouds.conf
$LAYOUT_PATH=~/.config/hypr/hyprlock/SF Pro.conf
$BACKGROUND = ~/Di3go0-0_Dots/Resources/wallpapers/Anime & Illustration/burningcherry.jpeg
source = $LAYOUT_PATH
