$DD01 = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/IMG0020.jpg
$OSAKA = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/osaka.jpg
$BURNINGCHERRY = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/burningcherry.jpeg

# Preload
preload = $DD01
preload = $OSAKA
preload = $BURNINGCHERRY

wallpaper {
    monitor = eDP-2
    path = $BURNINGCHERRY
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = $BURNINGCHERRY
    fit_mode = cover
}

splash = true

