$LOCKSCREEN = hyprlock

general {
    lock_cmd = $LOCKSCREEN
    unlock_cmd = pkill -x hyprlock
    before_sleep_cmd = $LOCKSCREEN
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = $LOCKSCREEN
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
