# ────────────────────────────────────────────────────────────
#  Hyprlock — minimal blur with ringed input
# ────────────────────────────────────────────────────────────

$LAYOUT_PATH=~/.config/hypr/hyprlock/SF Pro.conf
$BACKGROUND = /home/diego/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/itachi.jpg
source = $LAYOUT_PATH
