$LOVE = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/My love.jpeg
$DD01 = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/IMG0020.jpg
$OSAKA = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/osaka.jpg
$SAMURAI = ~/Di3go0-0_dots/Resources/wallpapers/Japoneses/fantasy-samurai-kimono-full-moon.jpg
$BURNINGCHERRY = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/burningcherry.jpeg
$SWORD = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/sword-8k-wallpaperjpg
$SWORD2 = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/sword-red-eyes.jpg
$NIGHT = ~/Di3go0-0_dots/Resources/wallpapers/Anime & Illustration/night-city-full-moon.jpg

# Preload
preload = $DD01
preload = $OSAKA
preload = $BURNINGCHERRY
preload = $SWORD

wallpaper {
    monitor = eDP-2
    path = $SAMURAI
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = $SWORD2
    fit_mode = cover
}

splash = true

