format = """\
($directory)\
$os\
$git_branch\
$fill\
$nodejs\
$rust\
$golang\
$php\
$bun\
$java\
$dotnet\
$c\
$conda\
$zig\
$python\
$cmd_duration\
$time\
\n$character\
"""

# Disable the blank line at the beginning of the prompt
add_newline = true

# Command timeout
command_timeout = 3600000

# Kanagawa Dragon color and style settings
palette = "kanagawa_dragon"

[fill]
symbol = ' '

[palettes.kanagawa_dragon]
arrow = "#DCD7BA"      # Light bone color, soft and visible
os = "#C4B28A"         # Warm yellow tone of dragonYellow
directory = "#8BA4B0"  # Soft sky blue, dragonBlue2
git = "#C4746E"        # Soft red, dragonRed
duration = "#957FB8"   # Soft purple, oniViolet
text_color = "#C5C9C5" # Light color, dragonWhite
text_light = "#2A2A37" # Dark gray, sumiInk4

# Pink mustache icon for the prompt
[character]
#(fg:#A3BE8C)
# 󱗞 ⚛  ❛❟❛ ☣︎  ❟❛❟ ☢ ✇
success_symbol = "[Aᴋᴀᴛsᴜᴋɪ ☁](fg:#957FB8) " # Mustache in dark pink tone
error_symbol = "[Aᴋᴀᴛsᴜᴋɪ ✇](fg:red)"       # Mustache in red if there is an error



# User settings
[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[󱗞 $user](fg:$style) ' # Mustache before the username
disabled = false
show_always = true

# Directory settings
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[cmd_duration]
format = " took [ $duration]($style) "
style = "bold fg:duration"
min_time = 500

[git_branch]
format = "-> [$symbol$branch]($style) "
style = "bold fg:git"
symbol = " "                           # Branch with oriental touch

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "fg:text_color bg:git"

[docker_context]
disabled = true
symbol = " "

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))](fg:#FF9E3B)($style)'
symbol = " "
version_format = "${raw}"

[java]
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'
version_format = "${raw}"
symbol = " "
disabled = false

[dotnet]
symbol = ""
format = '[[ $symbol ($version) ](fg:#9CDCFE)]($style)'
version_format = "${raw}"
disabled = false

[c]
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'
symbol = " "
version_format = "${raw}"
disabled = false

[zig]
format = '[[ $symbol ($version) ](fg:#FFA066)]($style)'
version_format = "${raw}"
disabled = false

[bun]
version_format = "${raw}"
format = '[[ $symbol ($version) ](fg:#DCD7BA)]($style)'
disabled = false

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#87a987)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#FF9E3B)]($style)'

[time]
disabled = false
time_format = "%R"                           # Hour:Minute Format
format = '[[   $time ](fg:#8BA4B0)]($style)'


